### ISSUE TITLE
ENOENT error while installing cordova-fabric-plugin

### ISSUE THREAD

**Issue by Gasorimplat** [nifino/twitter-digits-plugin#1]
Hello!
I'm having this error installing fabric in a ionic project
![error](https://cloud.githubusercontent.com/assets/12896955/16120977/d5ea694e-33b7-11e6-8944-6ab77fac005a.png)

some help? (console have administrative privileges)

**Comment by hahnml** [comment]
Hello!

From the screenshot it seems that you want to install the "cordova-fabric-plugin" from npm registry: https://www.npmjs.com/package/cordova-fabric-plugin. Therefore, the repository you are looking for should be this one: https://github.com/sarriaroman/FabricPlugin.

We provide a Cordova/Ionic plugin for Twitter Digits phone number login (https://docs.fabric.io/android/digits/digits.html) and not for Fabric in general.

Sorry, but hopefully @sarriaroman can help you!
